
			<!-- BEGIN MENUBAR-->
			<div id="menubar" class="menubar-inverse ">
				<div class="menubar-fixed-panel">
					<div>
						<a class="btn btn-icon-toggle btn-default menubar-toggle" data-toggle="menubar" href="javascript:void(0);">
							<i class="fa fa-bars"></i>
						</a>
					</div>
					<div class="expanded">

					</div>
				</div>
				<div class="menubar-scroll-panel">

					<!-- BEGIN MAIN MENU -->
					<ul id="main-menu" class="gui-controls">

						<!-- BEGIN DASHBOARD -->
						<li id="sidebar-home">
							<a href="<?php echo BASE.'home'?>">
								<div class="gui-icon"><i class="md md-home"></i></div>
								<span class="title">Home</span>
							</a>
						</li><!--end /menu-li -->
						<!-- END DASHBOARD -->

						<!-- BEGIN QUOTATION -->
						<li id="sidebar-quotation">
							<a href="<?php echo BASE.'quotation'?>">
								<div class="gui-icon"><i class="glyphicon glyphicon-list-alt"></i></div>
								<span class="title">Cotações</span>
							</a>
						</li><!--end /menu-li -->
						<!-- END QUOTATION -->


						<!-- BEGIN REPORTS -->
						<li id="sidebar-reports">
							<a href="<?php echo BASE.'report'?>">
								<div class="gui-icon"><i class="fa fa-line-chart"></i></div>
								<span class="title">Relatórios</span>
							</a>
						</li><!--end /menu-li -->
						<!-- END REPORTS -->

						<!-- BEGIN Customers -->
						<li id="sidebar-costumer">
							<a href="<?php echo BASE.'customer'?>" >
								<div class="gui-icon"><i class=" glyphicon glyphicon-plus"></i></div>
								<span class="title">Clientes</span>
							</a>
						</li><!--end /menu-li -->
						<!-- END Costumers -->

						<!-- BEGIN ADMIN -->
						<li id="sidebar-reports">
							<a href="../../html/charts/charts.html" >
								<div class="gui-icon"><i class="glyphicon glyphicon-user"></i></div>
								<span class="title">Admin</span>
							</a>
						</li><!--end /menu-li -->
						<!-- END ADMIN -->

					</ul><!--end .main-menu -->
					<!-- END MAIN MENU -->

					<div class="menubar-foot-panel">
						<small class="no-linebreak hidden-folded">
							<span class="opacity-75">Copyright &copy; 2016</span> <strong>FollowMeUP</strong>
						</small>
					</div>
				</div><!--end .menubar-scroll-panel-->
			</div><!--end #menubar-->
			<!-- END MENUBAR -->

