    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-custom">
                <div class="panel-heading">
                    <a id="logo" href="<?php echo BASE; ?>">
                        <img class="img-responsive" src="<?php echo IMG; ?>hxphp-logo.png" alt="">
                    </a>
                </div>
                <div class="panel-body">
                    <h4 class="alert alert-success">
                        HXPHP Framework!
                    </h4>
                    <p>
                        <a class="btn btn-success btn-xs" href="" title="HXPHP" target="_blank">área de membros</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
