<!-- BEGIN BANDED TABLE -->
						<div class="row">
							<div class="col-md-12">
								<div class="card">
									<div class="card-body floating-label">
										<form class="form" role="form">
											<!-- ROW START -->
											<div class="row">
											<!-- TERMINAL NUMBER START -->
												<div class="col-sm-2">
													<div class="form-group">
														<input type="text" class="form-control input-sm" id="customerID">
														<!-- !@# Fazer conexao para puxar numero cliente terminal -->
														<label for="customerID">N. Cliente Terminal</label>
													</div>
												</div>
												<!-- TERMINAL NUMBER END -->
												<!-- QUOTATION NUMBER START -->
												<div class="col-sm-1">
													<div class="form-group">
														<input type="text" class="form-control input-sm" id="quotationNumber">
														<label for="quotationNumber">N. Cotação</label>
													</div>
												</div>
												<!-- QUOTATION NUMBER END -->
												
												<!-- QUOTATION NUMBER START -->
												<div class="col-sm-1">
													<div class="form-group">
														<input type="text" class="form-control input-sm" id="value">
														<label for="value">Valor</label>
													</div>
												</div>
												<!-- QUOTATION NUMBER END -->
												<!-- QUOTATION NUMBER START -->
												<div class="col-sm-1">
													<div class="form-group">
														<input type="text" class="form-control input-sm" id="finalValue">
														<label for="finalValue">Valor Final</label>
													</div>
												</div>
												<!-- QUOTATION NUMBER END -->
												<!-- QUOTATION NUMBER START -->
												<div class="col-sm-1">
												<div class="form-group floating-label">
														<select id="priority" name="priority" class="form-control input-sm">
															<option value="">&nbsp;</option>
															<option value="A">A</option>
															<option value="B">B</option>
															<option value="C">C</option>
															<option value="D">D</option>
														</select>		
														<label for="priority">Prioridade</label>
														</div>										
												</div>											
												<!-- QUOTATION NUMBER END -->
												<!-- QUOTATION NUMBER START -->
												<div class="col-sm-1">
													<div class="form-group">
														<input type="text" class="form-control input-sm" id="status">
														<label for="status">Status</label>
													</div>
												</div>
												<!-- QUOTATION NUMBER END -->
												<!-- QUOTATION NUMBER START -->
												<div class="col-sm-1">
												<div class="form-group floating-label">
														<select id="commuWay" name="commuWay" class="form-control input-sm">
															<option value="">&nbsp;</option>
															<option value="salesman">Vendedor</option>
															<option value="customer">Cliente</option> 
															</select>
														<label for="commuWay">Comun.</label>
														</div>										
												</div>											
											    <!-- QUOTATION NUMBER END -->
												<!-- QUOTATION NUMBER START -->
												
												<div class="col-sm-1">
												<div class="form-group">												
												<div class="col-sm-1">
													<label class="checkbox-inline checkbox-styled checkbox-primary checkboxCustom">
														<input  type="checkbox" value="option1"><span>Conf.</span>
													</label>
													</div>
												</div><!--end .col -->
											</div><!--end .form-group -->						
											    <!-- QUOTATION NUMBER END -->
											    <!-- QUOTATION NUMBER START -->
												<div class="col-sm-2">
												<div class="form-group floating-label">
														<select id="dealerUserID" name="dealerUserID" class="form-control input-sm">
															<option value="">&nbsp;</option>
															<option value="1">Vendedor 1</option>
															<option value="2">Vendedor 2</option>
															<option value="3">Vendedor 3</option> 
															<option value="4">Vendedor 4</option>  
															</select>
														<label for="dealerUserID">Vendedor</label>
														</div>										
												</div>											
											    <!-- QUOTATION NUMBER END -->	
											    
											    <!-- QUOTATION NUMBER START -->
												<div class="col-sm-2">
													<div class="form-group">
														<div class="input-group date" id="demo-date">
															<div class="input-group-content">
																<input id="sendDate" name="sendDate" type="text" class="form-control input-sm">
																<label>Data Proposta</label>
															</div>
															<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
														</div>
													</div>
												</div>
												<!-- QUOTATION NUMBER END -->
												<!-- QUOTATION NUMBER START -->
												<div class="col-sm-2">
													<div class="form-group">
														<div class="input-group date" id="demo-date2">
													<div class="input-group-content">
														<input id="insertionDate" name="insertionDate" type="text" class="form-control input-sm">
														<label>Data Envio Proposta</label>
													</div>
													<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
												</div>
													</div>
												</div>
												<!-- QUOTATION NUMBER END -->
																							
												<div class="card-actionbar-row">
												<button type="submit" class="btn btn-flat btn-primary ink-reaction btn-quotation">Adicionar Cotação</button>
											</div>
											</div>
										</form>
									</div><!--end .card-body -->
								</div><!--end .card -->
							</div><!--end .col -->
						</div><!--end .row -->
						<!-- END BANDED TABLE -->


						

				<hr class="ruler-xxl"/>



						<div class="row">
							<div class="col-md-12">
								<div class="card">
									
										<div class="col-md-4">
								<div class="card card-underline">
									<div class="card-head">
										<header>Header</header>
										<div class="tools">
											<div class="btn-group">
												<a class="btn btn-icon-toggle btn-refresh"><i class="md md-refresh"></i></a>
												<a class="btn btn-icon-toggle btn-collapse"><i class="fa fa-angle-down"></i></a>
												<a class="btn btn-icon-toggle btn-close"><i class="md md-close"></i></a>
											</div>
										</div>
									</div><!--end .card-head -->
									<div class="card-body">
										<p>Ad ius duis dissentiunt, an sit harum primis persecuti, adipisci tacimates mediocrem sit et. Id illud voluptaria omittantur qui, te affert nostro mel. Cu conceptam vituperata temporibus has.</p>
									</div><!--end .card-body -->
								</div><!--end .card -->
							</div><!--end .col -->

							<div class="col-md-4">
								<div class="card card-underline">
									<div class="card-head">
										<header>Header</header>
										<div class="tools">
											<div class="btn-group">
												<a class="btn btn-icon-toggle btn-refresh"><i class="md md-refresh"></i></a>
												<a class="btn btn-icon-toggle btn-collapse"><i class="fa fa-angle-down"></i></a>
												<a class="btn btn-icon-toggle btn-close"><i class="md md-close"></i></a>
											</div>
										</div>
									</div><!--end .card-head -->
									<div class="card-body">
										<p>Ad ius duis dissentiunt, an sit harum primis persecuti, adipisci tacimates mediocrem sit et. Id illud voluptaria omittantur qui, te affert nostro mel. Cu conceptam vituperata temporibus has.</p>
									</div><!--end .card-body -->
								</div><!--end .card -->
							</div><!--end .col -->

							<div class="col-md-4">
								<div class="card card-underline">
									<div class="card-head">
										<header>Header</header>
										<div class="tools">
											<div class="btn-group">
												<a class="btn btn-icon-toggle btn-refresh"><i class="md md-refresh"></i></a>
												<a class="btn btn-icon-toggle btn-collapse"><i class="fa fa-angle-down"></i></a>
												<a class="btn btn-icon-toggle btn-close"><i class="md md-close"></i></a>
											</div>
										</div>
									</div><!--end .card-head -->
									<div class="card-body">
										<p>Ad ius duis dissentiunt, an sit harum primis persecuti, adipisci tacimates mediocrem sit et. Id illud voluptaria omittantur qui, te affert nostro mel. Cu conceptam vituperata temporibus has.</p>
									</div><!--end .card-body -->
								</div><!--end .card -->
							</div><!--end .col -->
										
						
									
								</div><!--end .card -->
							</div><!--end .col -->
						</div><!--end .row -->
		