		<script src="<?php  echo JS; ?>/libs/jquery/jquery-1.11.2.min.js"></script>
	    <script src="<?php  echo JS; ?>/libs/jquery/jquery-migrate-1.2.1.min.js"></script>
	    <script src="<?php  echo JS; ?>/libs/bootstrap/bootstrap.js"></script>
	    <script src="<?php  echo JS; ?>/libs/spin.js/spin.js"></script>
	    <script src="<?php  echo JS; ?>/libs/autosize/jquery.autosize.js"></script>	  
	    <script src="<?php  echo JS; ?>/libs/nanoscroller/jquery.nanoscroller.js"></script>	    
		<script src="<?php  echo JS; ?>/_build/source/App.min.js"></script>
		<script src="<?php  echo JS; ?>/_build/source/AppNavigation.min.js"></script>
		<script src="<?php  echo JS; ?>/_build/source/AppOffcanvas.min.js"></script>
		<script src="<?php  echo JS; ?>/_build/source/AppCard.min.js"></script>
		<script src="<?php  echo JS; ?>/_build/source/AppForm.min.js"></script>
		<script src="<?php  echo JS; ?>/_build/source/AppNavSearch.min.js"></script>
		<script src="<?php  echo JS; ?>/_build/source/AppVendor.min.js"></script>
	
		 <?php
	 	echo $add_js;
		?>
		<script src="<?php  echo JS; ?>/_build/demo/Demo.min.js"></script>
		
	</body>
</html>