	<!doctype html>
	<html lang="pt-br">
		<head>
			<title>WAGO Follow-UP</title>

			<!-- BEGIN META -->
			<meta charset="utf-8">
			<meta name="viewport" content="width=device-width, initial-scale=1.0">
			<meta name="keywords" content="your,keywords">
			<meta name="description" content="Short explanation about this website">
			<!-- END META -->

			<!-- BEGIN STYLESHEETS -->
			<link rel="shortcut icon" href="<?php echo IMG; ?>/favicon.ico" type="image/x-icon">
			<link rel="stylesheet" href="<?php echo CSS; ?>/main.min.css" type="text/css">	
			<link type="text/css" rel="stylesheet" href="<?php echo CSS; ?>/bootstrap.min.css" />
			<link type="text/css" rel="stylesheet" href="<?php echo CSS; ?>/materialadmin.min.css" />
			<link type="text/css" rel="stylesheet" href="<?php echo CSS; ?>/font-awesome.min.css?1422529194" />
			<link type="text/css" rel="stylesheet" href="<?php echo CSS; ?>/material-design-iconic-font.min.css" />	

			<?php 
				echo $add_css;		
			?> 

		</head>

